apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgBr8bsYcy+xYbV0qHub22smfDasRpeXEFJlY5oNUbIfuhK2thT3D8/jqOo6esiL5nqhZTjT1JUYwN+jwFPeSRLgzoZiJSLUWuQwhejz2q3bU4dkxnOWaJHEuKL160AEOh6gc+DbagofprkKPgwe2qS8MN2E9RUJtL8us+9mlZSXSRgodzWapsp06LeFj7uJbxbQOBgDxNQyBS2QJpofp0En7hX4Q1ZohuOA9v078GB5aZdjCnkzfXtvFDTKNbqzwrFNi43CHgEm81DJUn/CFeedbvYsKaBS+5E395wXS46sPa19ekQKc+smhAANvF0ESKCKVAtNVXuPr6YjgusPJJ6sAldeQPasz8nfm29UZbUy50t2FFNS5F4ygc4+4K02zwBR9/aDb62OkRdCQFxgodvBgeiZlTbbEHVpePnAC5fteC2/dx1IYC4gDorCuCXkMGRbL/PpOrod41kRZHm0VQTJjofdu3Gq45usCDu+vQDfiDAY1SaNPDw/dhmkGWfDF0RrLlm0ExZ4XpNcSx1YFFunBJnXQTew70HNnjZTgHLnK/acSNvtDMkR2jfmGJNhHa7JIT+dIJtp03O7wFbX80F9j0asPQPD70hXlJ25DK49A4RD0XrsIxW6UVPu2T4tRUuw7n7wk4iSRGjZ3gWXm07uAciNx375WVJRQiQ79DRkoTbH7RBiD4p5VeAfECfd7LUR3xoWQ6spkA==
    username: AgBfx3SUZbblMN3nMD7KUei3WFZOh4aH2WrMqefvFTJLd95G8vnO0T47GZUascaFsykRTeFGD31pt8DHb0r567FroVXx5eGUP0sMZWcWv3Hg2UOui9GjgAR5Y1JDs0wmKyHWf0tvrnkLqndjwk6163OV4ICvPutiWfg4pGqb533+LDqhNbDgMG8y7sQIHPW4P01E+3E0r5wFiJw/D+Yc4sL/zX65PPNdij/CtH43dOtvgE8Y8PKqFIYYYApgN8QqKoQ7uShDQKlV7RBRQn7dzbx9zNhdxxYeuHYi7jUMsSpb+8MIEqRQxSGx/2kSHG3Q62URJHjC1DzLZpi2t8LTqbt1y9O623XWwWw6AO61dtEHnopzHd2pCZXZok6ZsOJShZe96iLubP79s8+kyw4NQQLJMc3FzptRrxQGPiTX2P6/eqDl0kPGtA87klmJ1+VHb9vtXDPWpZRVXrtW3D7h2diasto6riXz4fRL0y4F1f9BipDnimKEv6g2UUiDq7sUXRI+l0+jhlzR5TbyA8kvgEquGiXQyAJmwlVSTTpt0AL64CWTeiyQC62NLJhQtkzPyjiC6TPwjCII7JWJANzgsBH5Gq0h597EVxYEIzZspHMKxY0sX/OZGqelFt9N5RAf+tziqvaLVfGKJHifUxGFJqN1AVTzTRqQ0+Iol5MqCMrNIuTLr4EIoE+D09Z88RVUkOGwOuXheHaBNg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
