apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-app-namespace
type: Opaque
data:
  database_password:  bXlzZWNyZXRwYXNzd29yZA==
  api_key: c29tZV9zZWNyZXRfYXBpX2tleQ==  # "some_secret_api_key"를 base64로 인코딩한 값
